UI/Controllers/GuildApplicantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Common;
using UI.GuildService;

namespace UI.Controllers
{
    public class GuildApplicantsController : ControllerBase
    {
        private readonly IGuildService _service;
        public GuildApplicantsController(IGuildService service)
        {
            this._service = service;
        }

        public ActionResult Index()
        {
            var model = _service.GetGuildApplicants(UserContext.Guild ?? 0);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Accept(GuildApplicationResolution model)
        {
            if (ModelState.IsValid)
            {
                model.Accepted = true;
                this._service.ResolveGuildApplication(model);
            }

            return RedirectToAction("Index", "Guild");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Decline(GuildApplicationResolution model)
        {
            if (ModelState.IsValid)
            {
                model.Accepted = false;
                this._service.ResolveGuildApplication(model);
            }

            return RedirectToAction("Index", "Guild");
        }
    }
}

UI/Views/GuildApplicants/Index.cshtml
@model List<UI.GuildService.GuildApplicant>
@{Layout = null;}
<table class="table table-striped">
    <thead>
        <tr>
            <td>Name</td>
            <td>Class</td>
            <td>Main spec</td>
            <td>Off spec</td>
            <td>Date of application</td>
            <td></td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var guildApplicant in Model)
        {
            <tr>
                <td>@guildApplicant.CharacterName</td>
                <td>@guildApplicant.ClassName</td>
                <td>@guildApplicant.PrimarySpecialization</td>
                <td>@guildApplicant.SecondarySpecialization</td>
                <td>@guildApplicant.DateOfApplication</td>
                <td>
                    @using (Html.BeginForm("Accept","GuildApplicants"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("ApplicationId", guildApplicant.Id)

                        <input type="submit" class="btn btn-primary" value="Accept"/>

                    }
                </td>
                <td>
                    @using (Html.BeginForm("Decline", "GuildApplicants"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("ApplicationId", guildApplicant.Id)

                        <input type="submit" class="btn btn-danger" value="Decline"/>
                    }
                </td>
            </tr>
        }
    </tbody>

</table>